### ISSUE TITLE
Factibilidad del proyecto

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/practica-de-costos-servitlax2#1]
[FACTIBILIDAD DEL PROYECTO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-costos-servitlax2/files/8158847/FACTIBILIDAD.DEL.PROYECTO.pdf)

**Comment by Abraham890** [comment]
Calificación:18 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
